IF OBJECT_ID('VENBANK', 'U') IS NOT NULL
BEGIN
  IF COL_LENGTH('VENBANK', 'PHYSICAL_ADDRESS') IS NULL
    ALTER TABLE [VENBANK] ADD [PHYSICAL_ADDRESS] NVARCHAR(MAX) NULL;

  IF COL_LENGTH('VENBANK', 'COUNTRY_OF_ORIGIN') IS NULL
    ALTER TABLE [VENBANK] ADD [COUNTRY_OF_ORIGIN] VARCHAR(100) NULL;

  IF COL_LENGTH('VENBANK', 'EMAIL') IS NULL
    ALTER TABLE [VENBANK] ADD [EMAIL] VARCHAR(255) NULL;

  IF COL_LENGTH('VENBANK', 'PHONE_NUMBER') IS NULL
    ALTER TABLE [VENBANK] ADD [PHONE_NUMBER] VARCHAR(20) NULL;

  IF COL_LENGTH('VENBANK', 'SORTCDE') IS NULL
    ALTER TABLE [VENBANK] ADD [SORTCDE] VARCHAR(20) NULL;

  IF COL_LENGTH('VENBANK', 'BRNCH') IS NULL
    ALTER TABLE [VENBANK] ADD [BRNCH] VARCHAR(255) NULL;

  IF COL_LENGTH('VENBANK', 'SWIFTCDE') IS NULL
    ALTER TABLE [VENBANK] ADD [SWIFTCDE] VARCHAR(20) NULL;
END;
