CREATE TABLE IF NOT EXISTS payment_queue_requests (
  id BIGINT NOT NULL AUTO_INCREMENT,
  queue_id VARCHAR(100) NOT NULL UNIQUE,
  payment_id VARCHAR(100) NOT NULL,
  bank_code VARCHAR(20) NOT NULL,
  payment_payload TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  attempts INT NOT NULL DEFAULT 0,
  last_error TEXT NULL,
  response_payload TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
